# Config du simulateur

device_types:

  motor_helios:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_dynamique_thruster.py'
    motor_type: 'propeller' # Or propeller
    max_force: 5 # N
    gain_power_tension: 45 # W/V
    offset_power_tension: -360 # W
    orientable: False
    pre_actuator: True # non utilisé

  imu_razor:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_imu.py'
    baudrate: 57600 # bps

  gps_globalsat_usb:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_gps.py'
    baudrate: 9600 # bps

  pololu_maestro:
    # Sa config est associée au package ros_maestro
    node_package: 'ros_maestro'
    node_type: 'simu_maestro.py'

  attopilot:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_attopilot.py'
    current_gain: 13.89
    voltage_gain: 49

  battery_lion_24v:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_batterie.py'
    max_voltage: 25.2 # V
    min_voltage: 18.0 # V
    max_energy: 20 # Ah

  power_distribution:
    node_package: 'ros_usv_simulator'
    node_type: 'simu_power_distribution.py'

  not_simulated: 'None'

simulation:
  dt: 0.05 # s | durée du pas interne de la simulation, supérieur à 0.1 ça crée des divergences
  dt_reel: 0.05 # s | cadencement réel des noeuds de sumilation
  duration: 100000 # s | durée de la simulation
  environnement:
    fluid_mass_density: 1000 # kg/m3
    current: # Pas encore implémenté
      x_force: 0.0 # N
      y_force: 0.0 # N
    authorized_zone:
      x_origin: 398898
      y_origin: 5354422
      x_offset: [-50, 50, 50,-50, -50] # m
      y_offset: [-50,-50, 50, 50, -50] # m

#==========================================================
# Config du robot

robot:

  simulated_characteristics:
    position:
      gps_lat: 48.33489 # deg
      gps_lon: -4.36421 # deg
      x: 398898 # m utm
      y: 5354422 # m utm
      z: 0.0
    orientation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
    speed:
      v_x: 0.0 # m/s
      v_y: 0.0 # m/s
      v_z: 0.0 # m/s
      v_roll: 0.0
      v_pitch: 0.0
      v_yaw: 0.0

  characteristics:
    axis_offset: [0,0,0]
    length: 1.2 # m
    height: 0.3 # m
    width: 0.6 # m
    mass: 20.0 # kg
    # TODO : intertial_matrix: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  actuators:

    motor_left:
      type: 'motor_helios'
      command:
        type: 'motor100'
        pwm:
          pin: 0
      orientation: 0
      position:
        x: -0.5 # m
        y: -0.4 # m
        z: 0.0 # m

    motor_right:
      type: 'motor_helios'
      command:
        type: 'motor100'
        pwm:
          pin: 1
      orientation: 0
      position:
        x: -0.5 # m
        y: 0.4 # m
        z: 0.0 # m

  pre_actuators:
    # Necessite le package ros_maestro
    maestro:
      type: 'pololu_maestro'
      config_path: 'config/ros_maestro/'

  sensors:
    imu:
      type: 'imu_razor'
    gps:
      type: 'gps_globalsat_usb'
    attopilot1:
      type: 'attopilot'
      battery: 'battery1'
      pwm:
        pin_voltage: 8
        pin_current: 9
    attopilot2:
      type: 'attopilot'
      battery: 'battery2'
      pwm:
        pin_voltage: 10
        pin_current: 11

  power_source:
    battery1:
      type: 'battery_lion_24v'
      start_voltage: 25 # V
    battery2:
      type: 'battery_lion_24v'
      start_voltage: 25 # V

  other:
    power_distribution:
      type: 'power_distribution'
      max_current: 30 # A
      resistance: 0.5 # Ohm
